language: go

go:
    - 1.5

install:
    - go get -v github.com/spf13/hugo

script: ./deploy.sh

env:
    global:
        - GITHUB_REPO: aubm/aubm-website
        - secure: ebr+O7cpZfZMwecYfGiJmEHLOt6R8RSF0X7DMLbUBfxjgqMwkxlN5I3Ocr90TAQU24NVv521oYJiS/K+q3FYkaa9o/jEEBG/MC61XbXPUgAzyGvN5Y9P9aZepHBG/y8lLvmhPfajSeavSmxkYluDafMQLt3WmL0jf0ZQKI04wux1AcK4KUKY8tWXTPITwIhxqwy4n8B4CNvDVi+NVgp0eZ/d4wJlsa1wW7gW/QhZDZ6IagfRboDWfOh+BLhuQdRTsB2f/KqzJDfOdkQ6A3mv5P/mqGGZFyLFdVFUsh/TQ92E73T/BuTBaiOb/3SH7sHC2pwcZiH3Srm80VDsu+mSwGwfamw05FiRLalbjXcyrdX6Qb8sGr3EualhwcOo+Qy3qTiMJMqw+nYQmUZIXo3hLeFdSfJkwA/WNhrBHABkVuFmZ43OlHyEOCa3q3swaOuJON41LM/p7PWozouSyL7XGdpFJoRgn2Zk98m70pDaIHNzhgIFO+6h0kEcotGJb3lNH4E1X2X+24Y8NNuqel2d+9ltETz83+y3hWZHzOQUvsCH6Zr025uhmdsrvykqcb3Kb7uIlq5F5GtduxyuVA62XfZO6BDnhhrntfwSB9/qh8eXL3OClVhD4HatUhwnhWpc32ZEiEqA69zHLc6Pn0MDComC3OkZYae8B1Vj2FKsc50=
