baseurl = "https://www.aubm.net/"
title = "Aubm"
theme = "noteworthy"

disqusShortname = "wwwaubmnet"
googleAnalytics = "UA-38043974-6"


[params]
# Main
email = "mailto:aur.baumann@gmail.com"
# facebook = "#"
twitter = "https://twitter.com/kendo5731"
# instagram = "#"
# tumblr = "#"
# reddit = "#"
# pinterest = "#"
# youtube = "#"
# weibo = "#"
# vk = "#"
linkedin = "https://www.linkedin.com/in/aurelienbaumann/"

# Writing
# medium = "#"
# blogger = "#"
# wordpress = "#"

# Creative & Visual
# dribbble = "#"
# behance = "#"
# deviantart = "#"
# flickr = "#"

# Programming
github = "https://github.com/aubm"
# stackoverflow = "#"
# gitlab = "#"
# codepen = "#"
