baseurl = "https://www.aubm.net/"
title = "Aubm"
theme = "noteworthy"

disqusShortname = "wwwaubmnet"
googleAnalytics = "UA-38043974-6"


defaultContentLanguage = 'en'
[languages]
  [languages.en]
#     title = 'Aubm'
#     contentDir = 'content/english'
    languageName = 'English'
    weight = 1
#     [languages.en.params]
#       linkedin = 'https://linkedin.com/whoever'
  [languages.fr]
#     title = 'Mon blogue'
    languageName = 'Français'
    weight = 2
#     contentDir = 'content/french'
    [languages.fr.params]
#       linkedin = 'https://linkedin.com/fr/whoever'
#       [languages.fr.params.navigation]
#         help = 'Aide'


[params]
# Main
email = "mailto:aur.baumann@gmail.com"
# facebook = "#"
twitter = "https://twitter.com/kendo5731"
# instagram = "#"
# tumblr = "#"
# reddit = "#"
# pinterest = "#"
# youtube = "#"
# weibo = "#"
# vk = "#"
linkedin = "https://www.linkedin.com/in/aurelienbaumann/"

# Writing
# medium = "#"
# blogger = "#"
# wordpress = "#"

# Creative & Visual
# dribbble = "#"
# behance = "#"
# deviantart = "#"
# flickr = "#"

# Programming
github = "https://github.com/aubm"
# stackoverflow = "#"
# gitlab = "#"
# codepen = "#"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
